version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c " pip install autopep8 && pip install redgreenunittest &&
      python manage.py runserver 0.0.0.0:7001 "
    volumes:
      - .:/code
    ports:
      - "7001:7001"
    depends_on:
      - db
