# Generated by Django 3.2.8 on 2021-12-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='feeling',
            name='feeling_need_relation',
            field=models.CharField(choices=[('m', 'Met Need'), ('u', 'Unmet Need')], default='m', max_length=1),
        ),
        migrations.CreateModel(
            name='FeelingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('feelings', models.ManyToManyField(to='nvc.Feeling')),
            ],
        ),
    ]
