# Generated by Django 3.2.8 on 2021-12-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0002_auto_20211230_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='feelings',
            field=models.ManyToManyField(to='nvc.Feeling'),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='FeelingGroup',
        ),
    ]
