# Generated by Django 3.2.8 on 2021-12-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0003_auto_20211231_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='NeedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('needs', models.ManyToManyField(to='nvc.Need')),
            ],
        ),
        migrations.CreateModel(
            name='FeelingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('feelings', models.ManyToManyField(to='nvc.Feeling')),
            ],
        ),
    ]
