# Generated by Django 3.2.8 on 2021-12-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0004_auto_20211231_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeling',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='feelinggroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='need',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='needgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='feelinggroup',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='needgroup',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
    ]
