# Generated by Django 3.2.8 on 2021-12-31 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0005_auto_20211231_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='need',
            old_name='feelings',
            new_name='met_feelings',
        ),
    ]
