# Generated by Django 3.2.8 on 2021-12-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0006_rename_feelings_need_met_feelings'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='unmet_feelings',
            field=models.ManyToManyField(related_name='unmet_feelings', to='nvc.Feeling'),
        ),
        migrations.AlterField(
            model_name='need',
            name='met_feelings',
            field=models.ManyToManyField(related_name='met_feelings', to='nvc.Feeling'),
        ),
    ]
