# Generated by Django 3.2.8 on 2021-12-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0007_auto_20211231_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='need',
            old_name='met_feelings',
            new_name='met_need_feelings',
        ),
        migrations.RenameField(
            model_name='need',
            old_name='unmet_feelings',
            new_name='unmet_need_feelings',
        ),
    ]
