# Generated by Django 3.2.8 on 2021-12-31 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0008_auto_20211231_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeling',
            name='feeling_need_relation',
        ),
        migrations.CreateModel(
            name='FeelingPoem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('poem', models.TextField(verbose_name='poem')),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvc.feeling')),
            ],
        ),
    ]
