# Generated by Django 3.2.8 on 2021-12-31 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0009_auto_20211231_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedPoem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('poem', models.TextField(verbose_name='poem')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvc.need')),
            ],
        ),
    ]
