# Generated by Django 3.2.8 on 2022-01-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0011_auto_20211231_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeling',
            old_name='status',
            new_name='met_or_unmet_need',
        ),
    ]
