# Generated by Django 3.2.8 on 2022-01-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0012_rename_status_feeling_met_or_unmet_need'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeling',
            name='met_or_unmet_need',
        ),
    ]
