# Generated by Django 3.2.8 on 2022-01-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0015_alter_feeling_met_or_unmet_need'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('poem', models.TextField(verbose_name='poem')),
                ('feelings', models.ManyToManyField(to='nvc.Feeling')),
                ('needs', models.ManyToManyField(to='nvc.Need')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='needpoem',
            name='need',
        ),
        migrations.DeleteModel(
            name='FeelingPoem',
        ),
        migrations.DeleteModel(
            name='NeedPoem',
        ),
    ]
